### ISSUE TITLE
Deque not in typing. Gives error when running webapp.py

### ISSUE THREAD

**Issue by avdabke** [rhettinger/modernpython#1]
Deque was not found in typing.
I am following your course in safari. 
I have python 3.6 on a windows 7 machine. 
For now, I removed Deque from my copy of pubsub.py and changed the type declarations on lines 23,24 to deque.

**Comment by rhettinger** [comment]
Try upgrading from 3.6.0.  Support for typing.Deque was added in Python 3.6.1.   See https://www.python.org/downloads/  If this fixes your issue, please comment and close.

**Comment by avdabke** [comment]
I installed 3.6.1 and I still get errors. Here is a copy-paste from my screen. I am running in a venv:

(modernpython) C:\Users\avdabke\Dropbox\python_work\modernpython\modernpython-master\pubsub>python -V
Python 3.6.1

(modernpython) C:\Users\avdabke\Dropbox\python_work\modernpython\modernpython-master\pubsub>pip freeze
bottle==0.12.13
colorama==0.3.7
hypothesis==3.7.3
mypy==0.501
py==1.4.33
pyflakes==1.5.0
pytest==3.0.7
typed-ast==1.0.3
typing==3.6.1

(modernpython) C:\Users\avdabke\Dropbox\python_work\modernpython\modernpython-master\pubsub>python -m mypy pubsub.py
pubsub.py:23: error: Invalid type "typing.Deque"
pubsub.py:24: error: Invalid type "typing.Deque"
pubsub.py:33: error: object has no attribute "appendleft"
pubsub.py:34: error: object has no attribute "appendleft"
pubsub.py:42: error: No overload variant of "islice" matches argument types [Deque?[Post?], builtins.int]
pubsub.py:45: error: Need type annotation for variable
pubsub.py:56: error: object has no attribute "__iter__"


--------------------------------------------

**Comment by avdabke** [comment]
Just to add...when I change the reference to deque[Post] from Deque[Post] on lines 23,24, all errors are resolved.

**Comment by avdabke** [comment]
I am closing this issue as right now it is a very minor thing and not even an annoyance and also that there is a workaround. Plus, I am sure typing/mypy will be updated very soon as it is still being developed.
