### ISSUE TITLE
__set_name__ explanation

### ISSUE THREAD

**Issue by ilmucio** [rhettinger/modernpython#3]
https://github.com/rhettinger/modernpython/blob/bda49e4e5ec86f2b3f5e28ba58bba8e0d13e3c62/validators.py#L7

From where the arguments of `__set_name__` (name and owner) are taken?

**Comment by rhettinger** [comment]
The ``__set_name__`` magic method lets you know where instances of this class are used and what attribute they are assigned to.  The *owner* field is the class where it is used.  The *name* field is the attribute name it is assigned to:

```
>>> class A:
	def __set_name__(self, owner, name):
		print(f'Calling class: {owner}\nAttribute name: {name}\n')

		
>>> class B:
	a = A()
	b = A()
	c = A()

	
Calling class: <class '__main__.B'>
Attribute name: a

Calling class: <class '__main__.B'>
Attribute name: b

Calling class: <class '__main__.B'>
Attribute name: c
```

**Comment by ilmucio** [comment]
Thanks, your answer is great :)!

**Comment by jeanmonet** [comment]
Can `__set_name__` be combined with `__init__` to have an initial default value?

```python
class IntDescr:
    def __set_name__(self, owner, name):
        self.private_name = f'_{name}'

    def __init__(self, default_value):
        # some magic?

    def __get__(self, obj, objtype=None):
        return getattr(obj, self.private_name)
    
    def __set__(self, obj, value):
        if not isinstance(value, int):
            raise ValueError
        setattr(obj, self.private_name, value)

class A:
    d = IntDescr(4)

a = A()
assert a.d == 4     # value set on __init__
```

Ideally, the value assignment in `__init__` would pass through the `__set__` method (and thus be checked by any filters set therein). Or would a metaclass be required in this case?

(I may be misunderstanding the use of descriptors)

One partial work-around I envisioned is:
```python
    def __init__(self, default_value=0):
        self.default_value = default_value

    def __get__(self, obj, objtype=None):
        return getattr(obj, self.private_name) if hasattr(obj, self.private_name) else self.default_value
```

**Comment by ANGEL1303** [comment]
@rhettinger class A is an attribute descriptor of class B?
