### ISSUE TITLE
Question on simulation for stats

### ISSUE THREAD

**Issue by redhermes** [rhettinger/modernpython#5]
Raymond,

I enjoyed your Big Ideas and Little Code video. I watched on O'Reilly Learning. 

As I thought about your approach to use simulations in place of analytic solutions I started wondering if the limitations of Python's pseudorandom number generator could cause a systematic bias to the calculated results. Do you know of any research that shows the approach you are promoting is statistically sound and how many significant digits can be assumed?  

Just asking?

Thanks.

**Comment by rhettinger** [comment]
You're somewhat same with Python's random module.  It uses the Mersenne Twister which is one of the best generators ever made and it has a enormously large period.  That said, if you're ever feeling worried about a simulation, switch to random.SystemRandom() which build off of physical sources of randomness amplified by crypto.

For research on resampling techniques, the go to book [Resampling: The New Statistics]( https://www.amazon.com/Resampling-statistics-Julian-Lincoln-Simon/dp/0534217206)

**Comment by redhermes** [comment]
Great! Thank you.
